### ISSUE TITLE
pretrained weigth name mismatch issue

### ISSUE THREAD

**Issue by emjay73** [yanwei-li/PanopticFCN#14]
Hi, first of all, thank you for the inspirational work!

I tried to download the pre-trained weight from the link you provided, 

especially the one with PanopticFCN-400 / R50 / 3x / faster threshold.

Download was successful, but the name of the weight is "panoptic_fcn_r50_512_3x.pth", which does not match the concept of it.

Also, its name is the same as the one with PanopticFCN-512 / R50 / 3x / faster threshold.

May I ask you to crosscheck the weight and its link?

Thanks!

**Comment by yanwei-li** [comment]
Hi, thanks for your interest. Actually, ```PanopticFCN-400``` share the same model with that in ```PanopticFCN-512```. That means it is trained with 512 size and test with 400 size, which would bring a better performance according to our experiments. And the faster version share the same model with the normal but with different inference setting, as declared in the README.

**Comment by emjay73** [comment]
Oh, I get it. Thanks!
