### ISSUE TITLE
about batch size

### ISSUE THREAD

**Issue by emjay73** [yanwei-li/PanopticFCN#18]
I realized that provided config files set IMGS_PER_BATCH as 16.
Did you assign 16 to IMGS_PER_BATCH when you train with 8 GPUs? Handling 2 images per GPU?
Or did you multiplied 16 by 8 and LR by 8 and iter by /8?
Are there any other hyperparameters that I have to change whenever I'd like to change a batch size or number of GPUs to reproduce the results?

**Comment by yanwei-li** [comment]
Hi, ```IMGS_PER_BATCH=16``` with 8 GPUS denotes 2 images/GPU. If you'd like to change the batch size, consider changing the LR and Iter linearly. For example, if ```IMGS_PER_BATCH``` is increased to 32, consider increasing LR to 2*LR while decreasing ```MAX_ITER ``` to 1/2 simultaneously. This ensures the total optimized epoch to be identical.

**Comment by emjay73** [comment]
May I ask why? 
Since you are using V100, I believe that you have pretty much room for a bigger batchsize, especially for the case like R-50-400 setting.

**Comment by yanwei-li** [comment]
Hi, because we want people who do not have V100 can still achieve a similar result in 1080Ti or 2080 Ti. So, we kept the most common setting, which is identical to other works.

**Comment by emjay73** [comment]
Oooh, that's really sweet of you! Thank you for your consideration. 
Actually, I'm using 2080ti and your comment somehow cheers me up.
Don't you think there could be a possibility that a small batch size hurts network performance because of an unstable statistic mean?

**Comment by yanwei-li** [comment]
Yes, actually it could be. But our goal is not to set up the best performance with a larger batch size. We'd like to find a better method for panoptic representation. So, we compare with previous works under the same setting to prove it. Of course, if you'd like to achieve better performance. Some other skills, like large batch size and more data augmentations, are recommended. BTW, for your reference, SyncBN for the backbone won't bring much improvement in our experiments.

**Comment by emjay73** [comment]
That's interesting. Thank you for sharing your experience of using SyncBN!
To sum up, you used the same config uploaded on Github to obtain the experimental results on the paper, not only yours but also others too. Am I right?

**Comment by yanwei-li** [comment]
Yes, you are right. It's a common setting.

**Comment by emjay73** [comment]
OK. Thank you. Have a good day!
