### ISSUE TITLE
What's the difference between work of Panoptic Deeplab?

### ISSUE THREAD

**Issue by jinfagang** [yanwei-li/PanopticFCN#2]
Hi,
What's the difference between work of Panoptic Deeplab which comes from here https://github.com/bowenc0221/panoptic-deeplab?

Do u compare the model runing time between then? And what's the model differences precisely

**Comment by yanwei-li** [comment]
Hi. PanopticFCN is different from Panoptic-Deeplab in various aspects, including network architecture, instance representation method (including things and stuff), processing procedure, inference time, loss function, and also performance, etc. Generally, Panoptic FCN represent things and stuff in a unified approach with high performance and efficiency, which surpasses previous box-based and box-free methods (including Panoptic Deeplab). 

Actually, we have compared the inference latency with Panoptic-Deeplab in Fig. 3 and Tab. 10 of the [main paper](https://arxiv.org/pdf/2012.00720.pdf). For more details, please refer to the paper of [Panoptic FCN](https://arxiv.org/pdf/2012.00720.pdf), as well as [Panoptic-DeepLab](https://arxiv.org/abs/1911.10194).

**Comment by jinfagang** [comment]
@yanwei-li Thank u for your dedicated explaination!
