### ISSUE TITLE
how to test image?

### ISSUE THREAD

**Issue by szh91** [yanwei-li/PanopticFCN#22]

**Comment by yanwei-li** [comment]
Hi, if you want to test a single image or video, you can directly use ```demo.py``` in detectron2 by change the code:
From
```
# To use demo for Panoptic-DeepLab, please uncomment the following two lines.
# from detectron2.projects.panoptic_deeplab import add_panoptic_deeplab_config  # noqa
# add_panoptic_deeplab_config(cfg)
```
To
```
from panopticfcn.config import add_panopticfcn_config  # noqa
add_panopticfcn_config(cfg)
```
Maybe this [issue#17](https://github.com/dvlab-research/PanopticFCN/issues/17#issue-899713371) could also help you.
