### ISSUE TITLE
About R101 corresponding configs and trained models

### ISSUE THREAD

**Issue by ShihuaHuang95** [yanwei-li/PanopticFCN#24]
Many thanks for this great work. I am wondering if you have any plan to release the R101 corresponding configs and trained models.

**Comment by ShihuaHuang95** [comment]
I have tried out the following config and just got PQ 45.6. 

MODEL:
  META_ARCHITECTURE: "PanopticFCN"
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-101.pkl
  MASK_ON: True
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [1.0, 1.0, 1.0]
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
  TRAIN: ("coco_2017_train_panoptic_separated",)
  TEST: ("coco_2017_val_panoptic_separated",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 1e-4
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  POLY_LR_POWER: 0.9
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
  WARMUP_METHOD: "linear"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 35.0
  IMS_PER_BATCH: 16
  MAX_ITER: 270000
  CHECKPOINT_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 1333
  MAX_SIZE_TEST: 1333
  MASK_FORMAT: "bitmask"
VERSION: 2

OUTPUT_DIR: "./PanopticFCN_r101_3x_FAM"

**Comment by yanwei-li** [comment]
Hi, Thanks for your interest. The config and performance seem right and normal.
