### ISSUE TITLE
How can I test an image with a trained model?

### ISSUE THREAD

**Issue by ding-Chen** [yanwei-li/PanopticFCN#26]
Hello author, how can I use the final model you placed on github to test an image of mine? I don't seem to see 'test.py'. Thank you for your answer!

**Comment by yanwei-li** [comment]
Hi, we construct the system based on Detectron2. So, maybe you should first install [Detectron2](https://github.com/facebookresearch/detectron2). For coco evaluation, you can follow the guide in README as follows. And for demo use, it is easy to use `demo.py` in Detectron2 with little modification. Maybe these issues #22 #17 could help you.
```
cd /path/to/detectron2
python3 projects/PanopticFCN/train.py --config-file <config.yaml> --num-gpus 8 --eval-only MODEL.WEIGHTS /path/to/model_checkpoint
```
