### ISSUE TITLE
Does the batch size matter?

### ISSUE THREAD

**Issue by dspcad** [yanwei-li/PanopticFCN#28]
Hi, 

I am trying to reproduce your result of COCO with the command below:
`python3 projects/PanopticFCN/train.py --config-file projects/PanopticFCN/configs/PanopticFCN-R50-1x.yaml --num-gpus 1 SOLVER.IMS_PER_BATCH 2`

I couldn't run it w/o "`SOLVER.IMS_PER_BATCH 2`" but my result was very poor.
Here is the command I run for the evaluation:
`python3 projects/PanopticFCN/train.py --config-file projects/PanopticFCN/configs/PanopticFCN-R50-1x.yaml --num-gpus 1 --eval-only MODEL.WEIGHTS output/model_final.pth`
![image](https://user-images.githubusercontent.com/22190436/127037733-3e9a1d35-e376-4163-8e8f-c0d65846a2e2.png)

I used your pretrained model and the result was way better than mine.
I would appreciate your help if you would like to point out where I went wrong.
Thanks.

**Comment by yanwei-li** [comment]
Hi, thanks for your interest. The batch size really matters. It is recommended to use batch 16 for training. Or you can try 400-size for training, and more images can be used in each batch.

**Comment by yghcats** [comment]
Hi, @yanwei-li @dspcad
Here is the command I run for the evaluation:
python3 projects/PanopticFCN/train.py --config-file projects/PanopticFCN/configs/PanopticFCN-R50-1x.yaml --num-gpus 1 --eval-only MODEL.WEIGHTS output/panoptic_fcn_r50_1x.pth

An error was encountered:
File "/home/gtx1080/anaconda3/envs/detectron/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 318)
My environment：python：3.6  PyTorch:1.7 cuda:10.1
I would appreciate your help if you would like to point out where I went wrong.
Thanks.

**Comment by yanwei-li** [comment]
Hi, it seems like environment error. Have you already installed the Detectron2 and test with no problem?
