### ISSUE TITLE
All 400 model leads to 512 size dowload link

### ISSUE THREAD

**Issue by jinfagang** [yanwei-li/PanopticFCN#3]
Hi, it seems all 400 model size leads to a 512 size download link? Where to download a 400 model ?

**Comment by yanwei-li** [comment]
Yes. In this setting, we use 512 size for training and 400 size for testing (400 is too small for seg, which brings little performance drop).

**Comment by jinfagang** [comment]
@yanwei-li You mean I just need to set input resize to 400 and using 512 trained model?

**Comment by yanwei-li** [comment]
Yes. You could use the script `PanopticFCN/configs/PanopticFCN-R50-400-3x.yaml` and the pretrained model with 512-size training.  Of course, it is also possible to retrain the model with 400 size, which will bring little performance drop. In our experiments, the gap between 400-size training and 512-size training (with 400-size testing) is about 0.2% PQ.

**Comment by jinfagang** [comment]
@yanwei-li thank u!
