### ISSUE TITLE
About training on Cityscapes 

### ISSUE THREAD

**Issue by wudaxianzi** [yanwei-li/PanopticFCN#30]
sorry to bother you , after reading all instructions and documentation about detectronc2 , I still don't know how to modify this project to train on cityscapes 
1. I've done followed dataset/README.md to separated Cityscapes and genarated (cityscapes_panoptic_train.json、cityscapes_panoptic_test.json...)
2. But in this peoject/configs/...yaml ,there all about coco_train, so whether should I write another config (.yaml)? 
And I don't know where to modify to locate or link to my cityscapes?
3.About the init WEIGHTS, which should I download to use?(still /data/detectronc2_modelzoo/basemodel/R-50-MSRA.pkl)
Sorry again if I missed something. 
Please give me some tips to run this project on training cityscapes. THX a lot >_<.

**Comment by yanwei-li** [comment]
Hi, thanks for your interest. Maybe you can refer to this issue #21. 
1. For the implementation, here is also a [fork](https://github.com/DdeGeus/PanopticFCN_cityscapes) modified for Cityscapes dataset. 
2. We also provide the R50-based model trained on Cityscapes, you can find the [model](https://drive.google.com/file/d/1j29Gf0r3qz3_KQ1uQiSRUuEKoB-osRgv/view?usp=sharing) and [metrics](https://drive.google.com/file/d/1vWaY_FhsIIxXBYX7IcvSavfw8ifqkgwO/view?usp=sharing).
3. For the initialized weights, the same Res50 model is used as in ```/data/detectronc2_modelzoo/basemodel/R-50-MSRA.pkl```

**Comment by wudaxianzi** [comment]
Thank you for your response~ I refered to the issue#21 and tried to run, But it came a new error :   
 (error in modulated_deformable_im2col_cuda: invalid device function) 
I wonder whether it's because my CUDA_VERSION(10.1) is not supported your project and I need higer version like 10.2..

**Comment by yanwei-li** [comment]
Hi, please make sure the Detectron2 has been compiled normally, and the inference process of raw PanopticFCN is conducted normally.

**Comment by wudaxianzi** [comment]
I can run the demo.py successfully. And so far I tried a few things.  I modified yaml DATALOADER_NUM_WORKERS to 0 and set num_gpus =1, then it works  . I don't know why I can't use distributed training(my device has 4 1080Ti) ,if  I change   NUM_WORKERS > 0, it does't work..and  come up a error that my process was terminated with signal SIGKILL. when starting training from iteration.

**Comment by yanwei-li** [comment]
It seems strange and could be an error in the running environment. Maybe you can try some other projects in Detectron2 and find out the reason.

**Comment by fatihyildiz-cs** [comment]
Hi, which config did you use to train and infer on the Cityscapes dataset? I used the suggested config [here](https://github.com/DdeGeus/PanopticFCN_cityscapes/blob/main/configs/cityscapes/PanopticFCN-R50-cityscapes.yaml) and successfully trained. But running the demo.py on the trained model results in the following error:

`AttributeError: Attribute 'thing_train_id2contiguous_id' does not exist in the metadata of dataset 'cityscapes_fine_panoptic_train_separated': metadata is empty.`

Thanks
