### ISSUE TITLE
I met a problem; the setting of max number of instances of the same category

### ISSUE THREAD

**Issue by AntonotnaWang** [yanwei-li/PanopticFCN#35]
To whom it may concern,

I met the following problem
RuntimeError: The expanded size of the tensor (100) must match the existing size (119) at non-singleton dimension 0.  Target sizes: [100, 182, 333].  Tensor sizes: [119, 182, 333]

May I ask is the above problem caused by the limitation of the max number of instances of the same category? Is the default setting is 100?
For my own dataset, the number of instances of the same category ("cell") in one image is often more than 100.

Thanks a lot

Anton

**Comment by AntonotnaWang** [comment]
> To whom it may concern,
> 
> I met the following problem
> RuntimeError: The expanded size of the tensor (100) must match the existing size (119) at non-singleton dimension 0. Target sizes: [100, 182, 333]. Tensor sizes: [119, 182, 333]
> 
> May I ask is the above problem caused by the limitation of the max number of instances of the same category? Is the default setting is 100?
> For my own dataset, the number of instances of the same category ("cell") in one image is often more than 100.
> 
> Thanks a lot
> 
> Anton

I managed to solve this problem by myself, It is because of the 15th line self.tensor_dim = cfg.MODEL.TENSOR_DIM in PanopticFCN/panopticfcn/gt_generate.py. cfg.MODEL.TENSOR_DIM seems to be 100. So it meant that the max number of instances of one category was 100.

**Comment by yanwei-li** [comment]
Dear Anton, thanks for your comment. You are right. The ```cfg.MODEL.TENSOR_DIM``` is used to indicate the max instance number. It varies with your dataset.
