### ISSUE TITLE
The " pretrained models" has the same URL

### ISSUE THREAD

**Issue by qingchunnianshao** [yanwei-li/PanopticFCN#37]
Hi there! I want to download the pretrained model with PanopticFCN-400 ,PanopticFCN-512  and PanopticFCN-600.But I find they have the same URL

**Comment by yanwei-li** [comment]
Hi, sorry for the late reply. For 400 size, we use 512 crops for training and 400 sizes for testing, because 400 is too small for segmentation training. And the model for 600 sizes should be different from them.
