### ISSUE TITLE
The purpose of embed_extractor in the thing/stuff_generator class

### ISSUE THREAD

**Issue by Dwrety** [yanwei-li/PanopticFCN#38]
Is it just a linear project layer? After acquiring the kernel weights from the KernelHead, I cannot find any activation layer following the layer itself. The weight seems to go directly to another Conv2d layer (embed_extractor) without any non-linearlity. If so, why not directly producing the kernels in the kernelhead instead?

**Comment by yanwei-li** [comment]
Hi, the ```embed_extractor``` is used to ensure the same channel of the generated kernel and that in the encoded feature.
Because the channel in encoded feature may change in different settings. So, the ```embed_extractor```  is adopted for adjustment.

**Comment by Dwrety** [comment]
I see, so it is basically a linear projection. Thanks for your clarification.
