### ISSUE TITLE
Could you please share the download link of R-50-MSRA.pkl ?

### ISSUE THREAD

**Issue by luoshuifeiyang** [yanwei-li/PanopticFCN#40]
I only found the basemodel  R-50.pkl in detectron2, but cannot find the R-50-MSRA.pkl.
Could you please share the download link of R-50-MSRA.pkl? Or R-50-MSRA.pkl is R-50.pkl, just the name is different?

**Comment by luoshuifeiyang** [comment]
Thank you

**Comment by yanwei-li** [comment]
Yes, you can find it in the detectron2 [here](https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MSRA/R-50.pkl).
