### ISSUE TITLE
How to use the demo.py file？

### ISSUE THREAD

**Issue by rongyiqing** [yanwei-li/PanopticFCN#46]
Please give me a detailed introduction of what needs to be changed.
![image](https://user-images.githubusercontent.com/95558460/172757192-0cb71f67-aca8-46f2-9d24-61627eba44c5.png)

**Comment by yanwei-li** [comment]
Hi, I guess this solution in issue #17 work for you.

The main reason is that the module panopticfcn has not been registered in Detectron2. So, you can simply add ```"panopticfcn": "PanopticFCN"``` to ```path_to_detectron2/detectron2/projects/__init__.py```. 
Then you can enjoy it by ```python3 demo/demo.py --config-file xxxx```.
Hope this could help you.

**Comment by rongyiqing** [comment]
That's what I did but no, it's the same problem that the questioner had before. Does that mean there's something missing from your process?

**Comment by rongyiqing** [comment]
I understand.
