### ISSUE TITLE
difference between "FPN-Summed" and "Semantic FPN"

### ISSUE THREAD

**Issue by valencebond** [yanwei-li/PanopticFCN#5]
What is the difference between "FPN-Summed" and "Semantic FPN" in table5, described in Section3.3? As far as I know, the high-resolution feature (1/4 scale of the input image) in Semantic FPN is also obtained by upsampling and element-wise summation

**Comment by yanwei-li** [comment]
Hi, the `FPN-Summed` represents that we upsample and sum the feature from FPN directly (without convs). And `Semantic FPN` includes convs in each upsample stage.

**Comment by valencebond** [comment]
thanks for your response
