### ISSUE TITLE
Why it works well?

### ISSUE THREAD

**Issue by CuberrChen** [yanwei-li/PanopticFCN#9]
Hi! The point of view in this paper is very new, but I don’t quite understand its working mechanism.Can you explain briefly？

**Comment by CuberrChen** [comment]
Or what is the difference between it and solov2?

**Comment by yanwei-li** [comment]
Hi! In general, Panoptic FCN encodes each object instance or stuff category into a specific kernel weight with the proposed kernel generator and produces the prediction by convolving the high-resolution feature directly. That means it produces the results in a simple _generate-kernel-then-segment_ workflow. 

The main difference between Panoptic FCN and SOLO V2 lies in that it represents Things and Stuff in a unified manner (encode each instance into a specific kernel), while SOLO V2 represents Things and Stuff differently (Things by locations and a separate branch for Stuff segmentation).

**Comment by CuberrChen** [comment]
The answer is very clear, thank you！
